manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: urob
      url-base: https://github.com/urob
    - name: slicemk
      url-base: https://github.com/slicemk
  projects:
    - name: zmk
      remote: urob
      revision: main
      import: app/west.yml
    - name: zmk
      remote: slicemk
      revision: dongle-pr
      import: app/west.yml
  self:
    path: config
